---
spark:
  app.name: user_activity_sink
  hive.exec.dynamic.partition: 'true'
  hive.exec.dynamic.partition.mode: nonstrict

input:
  type: kafka
  kafka.bootstrap.servers: localhost:9092
  subscribe: user-activity

transformer:
  type: key-value-as-is

sink:
  table.name: user_activity
  type: hive
  write.mode: append
